FROM ubuntu:18.04

RUN apt-get update -qq && DEBIAN_FRONTEND="noninteractive" apt-get install -qq \
  git \
  wget \
  python \
  apt-utils \
  python3 \
  tar \
  p7zip-full \
  software-properties-common \
  build-essential \
  curl zip unzip tar \  
  pkg-config \
  apt-transport-https \
  && apt-get clean -qq


RUN cd ${HOME} && wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null \
    && apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main' \
    && apt update && apt install -y kitware-archive-keyring && rm /etc/apt/trusted.gpg.d/kitware.gpg && apt update && apt install -y cmake ninja-build 

RUN wget --no-check-certificate -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
RUN add-apt-repository ppa:ubuntu-toolchain-r/test && add-apt-repository 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-15  main'
RUN apt-get update -qq && DEBIAN_FRONTEND="noninteractive" apt-get install -y \
  clang-15 && apt-get clean -qq

ADD ./entrypoint-build.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
