FROM ubuntu:22.04
RUN apt-get update -qq && DEBIAN_FRONTEND="noninteractive" apt-get install -qq \
  apt-transport-https \
  git \
  wget \
  python2 \
  python3 \
  tar \
  p7zip-full \
  cmake \
  software-properties-common \
  build-essential \
  curl zip unzip tar \  
  pkg-config \
  ninja-build \
  && apt-get clean -qq

RUN wget --no-check-certificate -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
RUN add-apt-repository 'deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-16  main'
RUN apt-get update -qq && DEBIAN_FRONTEND="noninteractive" apt-get install -qq \
  clang-16 && apt-get clean -qq

ADD ./entrypoint-build.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
